repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: ruff check --fix
        language: python
        types: [python]
        additional_dependencies: [".[dev]"]

    -   id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        additional_dependencies: [".[dev]"]

    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: [".[dev]"]